### ISSUE TITLE
Migrate docs tickets to GH issues

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza-docs#328]
## TODO
- [x] migrate tasks
- [x] remove team assignment
- [x] add labels
- [x] recheck drafts
- [x] submit drafts for a review
- [x] apply changes after review
- [x] convert drafts to issues
- [x] archive tasks
