### ISSUE TITLE
Document how auth assets can be exported on MSWindows

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza-docs#329]
## Link to forum where the issue was raised
https://forum.cortezaproject.org/t/corteza-server-auth-assets-export-segmentation-violation/429

## Recap
User has issue with setting up auth assets using Docker on Windows.

## Goal:
Add instructions on how to set up auth assets with Docker for a MSWindows environment

## Instructions to be added:
- create a folder on my desktop with .env, docker-compose.yaml files and templates folder
- in .env file add AUTH_DEVELOPMENT_MODE=true AUTH_ASSETS_PATH=/templates
- in docker-compose.yaml add services: server: volumes: ["./corteza-server/auth/assets:/templates", “./corteza-server/auth:/corteza/auth”]
- in templates folder copy-paste public and templates folders from corteza-server repo that are located in auth > assets

## Important things to note down:
- [ ] relative paths must be used
- [ ] explicitly grant access to the Docker engine

## TODO:
- [ ] create a dedicated docker section for MSWindows here https://docs.cortezaproject.org/corteza-docs/2022.9/integrator-guide/authentication/personalization.html or here https://github.com/cortezaproject/corteza-docs/blob/2023.3.x/src/modules/integrator-guide/pages/authentication
- [ ] add instructions
- [ ] provide screenshots if needed
- [ ] make sure instructions are clear and structured accordingly (follow the same structure we use in the docs)
