### ISSUE TITLE
Expand Algolia search model to include a nav menu

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza-docs#337]
## Description:
Improve Algolia search model to provide the most relevant/important/highlighted content (open with ctrl/command+K)

## Notes
- we will potentially need to modify our Algolia indexes
- you can find an example of how I think it should look like [here](https://mui.com/material-ui/guides/testing/#main-content) (press ctrl/cmd+k)

## TODO:
- [ ] research search component customisation & prepare a plan
- [ ] discuss plan with Tomaž
- [ ] add the changes

## Attachments
Current view

![Image](https://user-images.githubusercontent.com/85161724/204854028-210d7676-fb5c-4b49-b825-2eecc19610fd.png)

## Goal
**Important**: this is the idea; the content and style will be different for us.

![Image](https://user-images.githubusercontent.com/85161724/204852601-025648e9-8433-4764-804c-fba2a4d52fd9.png)
